name: release

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build devcontainer
        run: docker build -f .devcontainer/Dockerfile -t devcontainer .

      - name: Build website
        run: |
          git submodule update --init
          docker run \
            --entrypoint /bin/bash \
            -v $GITHUB_WORKSPACE:/src \
            --workdir /src \
            devcontainer \
            -c ./scripts/build.sh

      - name: Release
        run: ./scripts/deploy.sh
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.PUBLISH_SITE_TOKEN }}
